### ISSUE TITLE
Heroku: Push rejected, failed to compile Multipack app

### ISSUE THREAD

**Issue by fayazv** [taarifa/TaarifaTraders#3]
Following the instructions to deploy to heroku and running: 

```
heroku config:set BUILDPACK_URL=https://github.com/ddollar/heroku-buildpack-multi.git
```

Push rejected to **taarifa-traders** due to the following errors:

```
remote: ImportError: cannot import name md5
remote: ERROR:root:code for hash md5 was not found.
remote: Traceback (most recent call last):
remote:   File "/app/.heroku/python/lib/python2.7/hashlib.py", line 139, in <module>
remote:     globals()[__func_name] = __get_hash(__func_name)
remote:   File "/app/.heroku/python/lib/python2.7/hashlib.py", line 91, in __get_builtin_constructor
remote:     raise ValueError('unsupported hash type ' + name)
remote: ValueError: unsupported hash type md5
remote: ERROR:root:code for hash sha1 was not found.
remote: Traceback (most recent call last):
remote:   File "/app/.heroku/python/lib/python2.7/hashlib.py", line 139, in <module>
remote:     globals()[__func_name] = __get_hash(__func_name)
remote:   File "/app/.heroku/python/lib/python2.7/hashlib.py", line 91, in __get_builtin_constructor
remote:     raise ValueError('unsupported hash type ' + name)
remote: ValueError: unsupported hash type sha1
remote: ERROR:root:code for hash sha224 was not found.
remote: Traceback (most recent call last):
remote:   File "/app/.heroku/python/lib/python2.7/hashlib.py", line 139, in <module>
remote:     globals()[__func_name] = __get_hash(__func_name)
remote:   File "/app/.heroku/python/lib/python2.7/hashlib.py", line 91, in __get_builtin_constructor
remote:     raise ValueError('unsupported hash type ' + name)
remote: ValueError: unsupported hash type sha224
remote: ERROR:root:code for hash sha256 was not found.
remote: Traceback (most recent call last):
remote:   File "/app/.heroku/python/lib/python2.7/hashlib.py", line 139, in <module>
remote:     globals()[__func_name] = __get_hash(__func_name)
remote:   File "/app/.heroku/python/lib/python2.7/hashlib.py", line 91, in __get_builtin_constructor
remote:     raise ValueError('unsupported hash type ' + name)
remote: ValueError: unsupported hash type sha256
remote: ERROR:root:code for hash sha384 was not found.
remote: Traceback (most recent call last):
remote:   File "/app/.heroku/python/lib/python2.7/hashlib.py", line 139, in <module>
remote:     globals()[__func_name] = __get_hash(__func_name)
remote:   File "/app/.heroku/python/lib/python2.7/hashlib.py", line 91, in __get_builtin_constructor
remote:     raise ValueError('unsupported hash type ' + name)
remote: ValueError: unsupported hash type sha384
remote: ERROR:root:code for hash sha512 was not found.
remote: Traceback (most recent call last):
remote:   File "/app/.heroku/python/lib/python2.7/hashlib.py", line 139, in <module>
remote:     globals()[__func_name] = __get_hash(__func_name)
remote:   File "/app/.heroku/python/lib/python2.7/hashlib.py", line 91, in __get_builtin_constructor
remote:     raise ValueError('unsupported hash type ' + name)
remote: ValueError: unsupported hash type sha512
remote: Traceback (most recent call last):
remote:   File "/tmp/buildpackT7vtF/vendor/bpwatch/bpwatch", line 13, in <module>
remote:     import bp_cli
remote:   File "/tmp/buildpackT7vtF/vendor/bpwatch/bpwatch.zip/bp_cli.py", line 26, in <module>
remote:   File "/tmp/buildpackT7vtF/vendor/bpwatch/bpwatch.zip/logplex/__init__.py", line 1, in <module>
remote:   File "/tmp/buildpackT7vtF/vendor/bpwatch/bpwatch.zip/logplex/core.py", line 8, in <module>
remote:   File "/tmp/buildpackT7vtF/vendor/bpwatch/bpwatch.zip/logplex/packages/requests/__init__.py", line 58, in <module>
remote:   File "/tmp/buildpackT7vtF/vendor/bpwatch/bpwatch.zip/logplex/packages/requests/utils.py", line 23, in <module>
remote:   File "/tmp/buildpackT7vtF/vendor/bpwatch/bpwatch.zip/logplex/packages/requests/compat.py", line 7, in <module>
remote:   File "/tmp/buildpackT7vtF/vendor/bpwatch/bpwatch.zip/logplex/packages/requests/packages/__init__.py", line 3, in <module>
remote:   File "/tmp/buildpackT7vtF/vendor/bpwatch/bpwatch.zip/logplex/packages/requests/packages/urllib3/__init__.py", line 16, in <module>
remote:   File "/tmp/buildpackT7vtF/vendor/bpwatch/bpwatch.zip/logplex/packages/requests/packages/urllib3/connectionpool.py", line 12, in <module>
remote:   File "/tmp/buildpackT7vtF/vendor/bpwatch/bpwatch.zip/logplex/packages/requests/packages/urllib3/util.py", line 11, in <module>
remote: ImportError: cannot import name md5
remote: 
remote:  !     Push rejected, failed to compile Multipack app
remote: 
remote: Verifying deploy...
remote: 
remote: !   Push rejected to taarifa-traders.
remote: 
To https://git.heroku.com/taarifa-traders.git
 ! [remote rejected] fayaz-dev -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/taarifa-traders.git'
```

Running **heroku --version**:

```
heroku-toolbelt/3.32.0 (x86_64-darwin10.8.0) ruby/1.9.3
=== Installed Plugins
heroku-config
```

.buildpack file contains

```
https://github.com/heroku/heroku-buildpack-nodejs.git
https://github.com/heroku/heroku-buildpack-python.git#v36
```

**Comment by fayazv** [comment]
Modified .buildpack file to:

```
https://github.com/heroku/heroku-buildpack-nodejs.git
https://github.com/heroku/heroku-buildpack-python.git
```

**Comment by kynan** [comment]
That's useful to know, thanks!
